### PR TITLE
Add support for post-processing stack

### LINKED ISSUE #18: PostProcessingV2 not working on VXGI
Hi,Looooong,I found PostProessingV2 not working on VXGI.
Usually,i follow this steps can make it work.

1.Download postProcessingV2 package,(I have tried 2.1.7 and 2.0.17)
2.Add two scripts: Post Process Layer and Post Process Volume in the main Camera.
3. Set the camera layer into "Postprocessing"
4.Create a Post-Processing profile in the Assets file and assign it to the Camera's Post Process Volume component's Profile

Then,in the  Post Process Volume component ,click the is Global and add different effect on it will see the PostProcess effect.Like Vignette or sth else.

But in VXGI is not successful ,did I miss any steps?

### PR DESCRIPTION
**Pull request by Looooong**
This PR adds partial support for post-processing rendering. Further development will enable more functionalities of the post-processing stack.

Fixed: #18

### CODE REVIEW

**Comment by Looooong** [comment]
@jeske Can you help me test this out? I'm appreciated.

**Comment by jeske** [comment]
yes, ill try to run it tonight.

**Comment by Looooong** [comment]
Capture

@jeske When I take a look at the post-processing light meter, the luminance range doesn't seem to go past the middle of the curve graph (less than 0 EV). Is that a problem?

**Comment by Looooong** [comment]
So I was drawing everything on top of camera buffer, which doesn't support HDR color. Using an intermediate HDR render texture fix the problem.

**Pull request merged**
